from enum import Enum

class NotificationType(Enum):
    FRIEND_REQUEST_ACCEPTED = "FRIEND_REQUEST_ACCEPTED",
    FRIEND_REQUEST_REJECTED = "FRIEND_REQUEST_REJECTED",
    FRIEND_REMOVED = "FRIEND_REMOVED"